config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :profiles
  resources :groups do
    resources :events
  end
  resources :memberships
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "registrations" }

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  last_name     :string(255)
#  profile_image :string(255)
#  screen_name   :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  birthday      :date
#  user_id       :integer
#

class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :profile_image, ProfileUploader

  validates :first_name, :last_name, :screen_name, :birthday, :user_id, presence: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/admin/profiles_controller.rb
module Admin
  class ProfilesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Profile.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Profile.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @user = current_user
    @memberships = @user.memberships
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id if current_user
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :profile_image, :screen_name, :birthday)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile, html: { class: "form-block" }) do |f| %>
  <%= f.error_notification %>

    <p class="pull-left">Upload a Profile picture</p>
    <%= f.input :profile_image, as: :file, label: false, input_html: { class: "form-control" } %>
    <%= f.input :first_name, required: true, label: false, placeholder: "First Name", input_html: { class: "form-control" } %>
    <%= f.input :last_name, required: true, label: false, placeholder: "Last Name", input_html: { class: "form-control" } %>
    <%= f.input :screen_name, required: true, label: false, placeholder: "Screen Name", input_html: { class: "form-control" } %>
    <p class="pull-left">What is your Birthday?</p>
    <%= f.input :birthday, as: :date, start_year: Date.today.year - 99, order: [:month, :day, :year], required: true, label: false, placeholder: "Birthday", input_html: { class: "form-control" } %>
    <%= f.button :submit, class: "btn btn-info block" %>

<% end %>

app/views/profiles/_profile.html.erb
<div class="col-md-3">
  <div class="thumbnail profile">
    <div class="caption text-center">
      <%= link_to profile do %>
        <%= image_tag(profile.profile_image.large) if profile.profile_image? %>
      <% end %>
      <h3><%= link_to profile.screen_name, profile %></h3>
    </div>
  </div>
</div>

app/views/profiles/destroy.js.erb
$('.profile-destroy').bind('ajax:success', function(){
  $(this).closest('tr').fadeOut();
});

app/views/profiles/edit.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
  <h2>Editing Profile</h2>

  <%= render 'form' %>

  <%= link_to 'Show', @profile %> |
  <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/index.html.erb
<h1>All Profiles</h1>
<%= render @profiles %>

app/views/profiles/new.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
  <h2>Lets Setup Your Profile</h2>

  <%= render 'form' %>

  <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<div class="col-md-4">
  <%= image_tag(@profile.profile_image.large, class: "img-responsive profile-img") if @profile.profile_image? %>
  <h3><%= @profile.first_name %>'s Memberships</h3>
  <table class="table table-striped">
    <thead>
      <th>Memberships</th>
      <th>Joined</th>
    </thead>
    <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= link_to membership.group.name, group_path(membership.group.id) %></td>
        <td><%= membership.joined %></td>
      </tr>
    <% end %>
    <tbody>
  </table>
</div><!--end col-md-4-->
<div class="col-md-8">
  <% if can? :manage, @profile %>
    <p><%= link_to 'Edit Profile', edit_profile_path(@profile) %></p>
  <% end %>
  <h1><%= @profile.full_name %> <small>@<%= @profile.screen_name %></small></h1>
</div><!--end col-md-8-->