config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :profiles
  resources :groups do
    resources :events
  end
  resources :memberships
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "registrations" }

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id                       :integer          not null, primary key
#  user_id                  :integer
#  name                     :string(255)
#  description              :text(65535)
#  featured_image           :string(255)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  location_id              :integer
#  featured_image_file_name :string(255)
#

class Group < ActiveRecord::Base
  belongs_to :user
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_one :location, dependent: :destroy
  has_many :events, dependent: :destroy
  accepts_nested_attributes_for :location
  mount_uploader :featured_image, FeaturedImageUploader

  validates :name, presence: true, uniqueness: true

  def since
    self.created_at.strftime("%B %d, %Y")
  end
end

app/controllers/admin/groups_controller.rb
module Admin
  class GroupsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Group.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Group.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @membership = Membership.new
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @events = @group.events.where('date >= ?', Date.today).order(:date)
    @memberships = @group.memberships
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.build_location
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id if current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:user_id, :name, :description, :featured_image, location_attributes: [:city, :state, :postal_code])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group, html: { class: "form-block" }) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, required: true, autofocus: true, label: false, placeholder: "Group Name", input_html: { class: "form-control" } %>
  <%= f.simple_fields_for :location do |p| %>
    <%= p.input :city, required: true, label: false, placeholder: "City", input_html: { class: "form-control" } %>
    <p class="pull-left">Please Choose a State from the dropdown list</p>
    <%= p.input :state, :collection => us_states, required: true, label: false, placeholder: "State", input_html: { class: "form-control" } %>
    <%= p.input :postal_code, required: true, label: false, placeholder: "Postal Code", input_html: { class: "form-control" } %>
  <% end %>
  <p class="pull-left">Add an Featured Image for you Group</p>
  <%= f.input :featured_image, as: :file, label: false, input_html: { class: "form-control" } %>
  <%= f.input :description,label: false, placeholder: "A brief description of your group", input_html: { class: "form-control" } %>
  <%= f.button :submit, class: "btn btn-info block" %>

<% end %>

app/views/groups/_group.html.erb
<div class="col-md-3">
  <div class="thumbnail group">
    <div class="caption text-center">
      <%= link_to group do %>
        <%= image_tag(group.featured_image.large) if group.featured_image? %>
      <% end %>
      <h3><%= link_to truncate(group.name, length: 25, separator: ' '), group, class: "group-name" %><br/><small><%= group.location.city %>, <%= group.location.state %></small></h3>
      <div class="form-container">
        <%= simple_form_for(@membership) do |f| %>
          <%= f.input :group_id, as: :hidden, input_html: { value: group.id } %>
          <%= f.submit "Join Group", class: "btn btn-info sm block join-btn" %>
        <% end %>
      </div>
      <% if can? :manage, group %>
        <%= link_to "<i class='fa fa-pencil-square'></i>".html_safe, edit_group_path(group), data: { confirm: "Are you sure you want to Edit this Group?" }, title: "Edit", class: "edit-link pull-left" %>
        <%= link_to "<i class='fa fa-times-circle'></i>".html_safe, group, method: :delete, data: { confirm: "Are you sure you want to Delete this Group?" }, title: "Delete", class: "delete-link pull-right" %>
        <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
<h2>Edit Your Group</h2>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>
</div><!-- end .col-md-4 -->

app/views/groups/index.html.erb
<div class="col-md-9">
  <h1>Find a Group, Join, &amp; Start Making New Friends!</h1>
  <p>Can't find a group right for you? Create your own group for others to join.</p>
</div>
<div class="col-md-3">
  <%= link_to 'Create a New Group', new_group_path, class: "btn btn-info block sm" %>
</div>
<div class="clearfix"></div>
<br/>

<div class="row">
  <%= render @groups %>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
<h2>Create a New Group</h2>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>
</div><!-- end .col-md-4 -->

app/views/groups/show.html.erb
<div class="col-md-4">
  <%= image_tag(@group.featured_image.large, class: "img-responsive group-img") if @group.featured_image? %>
  <h3>Group Members</h3>
  <hr/>
  <% @memberships.each do |member| %>
    <div class="col-md-3">
      <%= image_tag(member.user.profile.profile_image.medium, class: "img-responsive profile-img") if member.user.profile.profile_image? %>
    </div>
    <div class="col-md-9">
      <h4><%= member.user.profile.full_name %><br/><small>@<%= link_to member.user.profile.screen_name, profile_path(member.user.profile.id) %></small></h4>
    </div>
    <div class="clearfix"></div>
  <% end %>
</div><!--end col-md-4-->
<div class="col-md-8">
  <% if can? :manage, @group %>
    <%= link_to 'Edit Group', edit_group_path(@group) %>
  <% end %>
  <h1><%= @group.name %><br/><small><%= @group.location.city_state %></small></h1>
  <h3>Group Est. <small><%= @group.since %></small></h3>
  <p><%= @group.description %></p>
  <h3>Up Coming Events <%= link_to 'Add an Event', new_group_event_path(@group.id) if can? :manage, @group %></h3>
  <table class="table table-striped">
    <thead>
      <th>Event</th>
      <th>Venue</th>
      <th>Date</th>
    </thead>
    <tbody>
      <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, group_event_path(@group, event) %></td>
        <td><%= event.venue.name %></td>
        <td><%= event.date.strftime("%b %d, %Y") %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div><!--end col-md-8-->