config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :profiles
  resources :groups do
    resources :events
  end
  resources :memberships
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "registrations" }

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  group_id    :integer
#  name        :string(255)
#  venue_id    :integer
#  date        :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text(65535)
#

class Event < ActiveRecord::Base
  belongs_to :group
  has_one :venue, dependent: :destroy
  accepts_nested_attributes_for :venue

end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Event.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Event.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_group
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = @group.events.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.build_venue
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.group_id = @group.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to [@group, @event], notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [@group, @event], notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to group_events_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:group_id, :name, :venue_id, :date, :description, venue_attributes: [:name, :state, :city])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for([@group, @event], html: { class: "form-block" }) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name, required: true, label: false, placeholder: "Event Name", input_html: { class: "form-control" } %>
    <%= f.simple_fields_for :venue do |p| %>
      <%= p.input :name, required: true, label: false, placeholder: "Venue Name", input_html: { class: "form-control" } %>
      <p>Please Choose a State</p>
      <%= p.input :state, collection: us_states, required: true, label: false, input_html: { class: "form-control" } %>
      <%= p.input :city, required: true, label: false, placeholder: "City", input_html: { class: "form-control" } %>
    <% end %>
    <%= f.input :description, label: false, placeholder: "Event Description", input_html: { class: "form-control" } %>
    <p>When is the Event?<p>
    <%= f.input :date, as: :date, required: true, label: false, input_html: { class: "form-control" } %>
    <%= f.button :submit, class: "btn btn-info block" %>

<% end %>

app/views/events/edit.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
  <h1>Editing Event</h1>

  <%= render 'form' %>

  <%= link_to 'Show', group_events_path(@group, @event) %> |
  <%= link_to 'Back', group_events_path %>
</div>

app/views/events/index.html.erb
<h1>Listing Events</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Group</th>
      <th>Name</th>
      <th>Venue</th>
      <th>Date</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.group_id %></td>
        <td><%= event.name %></td>
        <td><%= event.venue.name %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', group_event_path(@group, event) %></td>
        <td><%= link_to 'Edit', edit_group_event_path(@group, event) %></td>
        <td><%= link_to 'Destroy', [@group, event], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back to Group', group_path(@group) %> | 
<%= link_to 'New Event', new_group_event_path %>

app/views/events/new.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
  <h1>New Event</h1>

  <%= render 'form' %>

  <%= link_to 'Back', group_events_path %>
</div>

app/views/events/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <h3><%= @group.name %> Presents</h3>
  <h1><%= @event.name %></h1>
  <h2><%= @event.venue.name %> - <small><%= @event.date.strftime("%B %d, %Y") %></small></h2>
  <p><%= @event.description %></p>
  <%= link_to 'Back to Group', group_path(@group) %> |
  <%= link_to 'Edit', edit_group_event_path(@group, @event) %>
</div>