config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :profiles
  resources :groups do
    resources :events
  end
  resources :memberships
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "registrations" }

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'

end

app/views/layouts/_main_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#oao-main-nav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Oak&Oceans", root_path, class: "navbar-brand", data: {no_turbolink: false} %>
    </div>
    <div class="collapse navbar-collapse" id="oao-main-nav">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.profile %>
                <li><%= link_to "View Profile", profile_path(current_user.profile.id) %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "My Groups", memberships_path %></li>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            </ul>
          </li>
          <li><%= link_to "Small Groups", groups_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Terms", terms_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></i>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oakandoceans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @body_class %>">

<%= render "layouts/main_nav" %>

<div class="container main-content">
  <%= yield %>
</div>

</body>
</html>